// Generated by CoffeeScript 1.7.1
(function() {
  var number, opposite, square;

  number = 42;

  opposite = true;

  if (opposite) {
    number = -42;
  }

  square = function(x) {
    return x * x;
  };

}).call(this);

//# sourceMappingURL=example.map
